version: '3'
networks:
  development:
  test:
services:
  db:
    image: postgres:13
    environment: 
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
    networks:
      - development
      - test
    volumes:
      - postgres:/data/postgres
  es:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    healthcheck:
      test: curl -s http://container:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200 
    networks:
      - development
      - test
  web:
    build: .
    tty: true
    stdin_open: true
    networks:
      - development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - es
    environment:
      ELASTIC_SEARCH_URL: 'es-container:9200'
      DATABASE_HOST: "db"
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "password"
      DATABASE_PORT: 5432
      EDITOR: "vim"
    volumes:
      - .:/holder:delegated
      - bundle:/usr/local/bundle
      - cache:/holder/tmp/cache
  web_test:
    image: holder_web
    container_name: holder-test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    stdin_open: true
    volumes:
      - .:/holder:delegated
      - bundle:/usr/local/bundle
      - cache:/holder/tmp/cache
    tty: true
    ports:
      - "9000:3000"
    networks:
      - test
    depends_on:
      - db
      - es
    environment:
      ELASTIC_SEARCH_URL: 'es-container:9200'
      DATABASE_HOST: "db"
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "password"
      DATABASE_PORT: 5432
      RAILS_ENV: test
      SWAGGER_DRY_RUN: 0
volumes:
  postgres:
  cache:
  bundle: 