# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: auto-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: docker-compose -f "docker-compose.yml" build
    
    - name: setup
      run:  docker-compose run --rm web rails db:create && docker-compose run --rm web rails db:migrate && docker-compose run --rm web bundle install

    - name: rubocop
      run: docker-compose run --rm web bundle exec rubocop
    
    - name: rspec
      run: make rspec